services:
  backend:
    container_name: monitor360-backend
    build:
      context: ./backend
    restart: unless-stopped
    env_file: ./.env
    environment:
      DB_SSL_MODE: ${DB_SSL_MODE:-require}
    ports:
      - "8000:8000"
    # Si no usas CA custom, no montes /certs
    # volumes:
    #   - ./certs:/certs:ro
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --workers 1
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/docs >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    # ⬇️ Requisitos para WireGuard dentro del contenedor
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
